# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-13 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garmantino', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='starred',
            field=models.BooleanField(default=False, help_text='Отмечено ли свойство звездочкой.', verbose_name='Звезданутый?'),
        ),
    ]
