# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-13 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garmantino', '0002_property_starred'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='article',
            field=models.CharField(default='Артикул', max_length=9, verbose_name='Артикул'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='cost',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
