# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-14 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garmantino', '0002_auto_20160713_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(max_length=300, null=True, verbose_name='Приоритетность'),
        ),
    ]
