# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-14 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garmantino', '0003_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(max_length=300, null=True, verbose_name='Описание'),
        ),
    ]
