# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-13 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garmantino', '0004_remove_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='short_info',
            field=models.CharField(default='размер не указан', max_length=50, verbose_name='Инфо-ия для Анимации'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='cost',
            field=models.FloatField(max_length=5, verbose_name='Цена'),
        ),
    ]
