# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-13 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garmantino', '0005_auto_20160913_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='garmantino.Category', verbose_name='Родительская категория'),
        ),
    ]
