# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-04 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garmantino', '0007_auto_20161003_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ManyToManyField(to='garmantino.Category', verbose_name='Категория'),
        ),
    ]
