# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-04 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garmantino', '0010_auto_20161004_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='categories',
        ),
    ]
