# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garmantino', '0003_auto_20160131_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('y', 'Не Используется'), ('n', 'Используется'), ('o', 'Устарела')], default='d', max_length=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('m', 'В Производстве'), ('y', 'Есть В Наличии'), ('n', 'Нет В Наличии'), ('o', 'Снят С Производства')], default='m', max_length=1),
        ),
    ]
