# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 20:01
from __future__ import unicode_literals

import apps.garmantino.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garmantino', '0005_auto_20160131_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.ImageField(null=True, upload_to=apps.garmantino.models.generate_category_image_filename),
        ),
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(null=True, upload_to=apps.garmantino.models.generate_item_image_filename),
        ),
    ]
