# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garmantino', '0006_auto_20160131_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='garmantino.Category'),
        ),
    ]
