# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 13:29
from __future__ import unicode_literals

import apps.garmantino.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garmantino', '0008_auto_20160131_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.ImageField(default='imgs\\default-category.jpg', upload_to=apps.garmantino.models.generate_category_image_filename),
        ),
        migrations.AlterField(
            model_name='category',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(upload_to=apps.garmantino.models.generate_item_image_filename),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('m', 'В Производстве'), ('y', 'Есть В Наличии'), ('n', 'Нет В Наличии'), ('o', 'Снят С Производства'), ('t', 'Шаблон')], default='m', max_length=1),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='property',
            name='value',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
