# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garmantino', '0012_auto_20160202_0218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ManyToManyField(to='garmantino.Category'),
        ),
    ]
