# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 14:17
from __future__ import unicode_literals

import apps.garmantino.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garmantino', '0013_auto_20160202_0329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Фото', 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['pub_date'], 'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.AddField(
            model_name='item',
            name='importance',
            field=models.CharField(choices=[('a', 'Очень Важный'), ('b', 'Важный'), ('c', 'Не Важный')], default='c', max_length=1, verbose_name='Приоритетность'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='garmantino.Category', verbose_name='Родительская категория'),
        ),
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.ImageField(default='imgs\\categories\\default-category.jpg', upload_to=apps.garmantino.models.generate_category_image_filename, verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='category',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Это то, в каком шестиугольнике будет находиться фото. Оставьте пустым, чтобы значение заполнилось автоматически', null=True, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('n', 'Не Используется'), ('y', 'Используется'), ('o', 'Устарела')], default='n', max_length=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(default='imgs\\items\\default-item.jpg', upload_to=apps.garmantino.models.generate_item_image_filename, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ManyToManyField(help_text='Выбирать мышкой и кнопкой ctrl. Столик может относиться к нескольким категориям!', to='garmantino.Category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название предмета'),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('m', 'В Производстве'), ('y', 'Есть В Наличии'), ('n', 'Нет В Наличии'), ('o', 'Снят С Производства'), ('t', 'Шаблон')], default='m', max_length=1, verbose_name='Статус производства'),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(help_text='Например - цвет', max_length=30, verbose_name='Имя свойства'),
        ),
        migrations.AlterField(
            model_name='property',
            name='order',
            field=models.IntegerField(default=0, help_text='В соответствии с этим номером сортируются свойства. Свойства с маленьким порядковым номером - сверху, с большим - снизу', verbose_name='Порядковый номер'),
        ),
        migrations.AlterField(
            model_name='property',
            name='value',
            field=models.CharField(blank=True, help_text='Например - красный', max_length=100, verbose_name='Значение свойства'),
        ),
    ]
