# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-07 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garmantino', '0014_auto_20160202_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemOnHomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('importance', models.CharField(choices=[('a', 'Очень Важный'), ('b', 'Важный'), ('c', 'Не Важный')], default='c', max_length=1, verbose_name='Приоритетность')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garmantino.Item', verbose_name='Предмет для главной')),
            ],
            options={
                'verbose_name': 'Предмет для главной страницы',
                'ordering': ['pub_date'],
                'verbose_name_plural': 'Предметы для главной страницы',
            },
        ),
    ]
