# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-12 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garmantino', '0016_auto_20160209_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemonhomepage',
            name='importance',
        ),
        migrations.AddField(
            model_name='itemonhomepage',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Это то, в каком шестиугольнике будет находиться фото. Оставьте пустым, чтобы значение заполнилось автоматически', null=True, verbose_name='Позиция'),
        ),
    ]
